services:
  postgres:
    image: postgres:16-alpine
    container_name: typer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - typer_pgdata:/var/lib/postgresql/data

volumes:
  typer_pgdata:
